// This file is generated by `npm run db:types` from supabase/schema.sql.
// Do not edit it manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          owner_id: string
          display_name: string | null
          image_url: string | null
          onboarding_completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          owner_id: string
          display_name?: string | null
          image_url?: string | null
          onboarding_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          owner_id?: string
          display_name?: string | null
          image_url?: string | null
          onboarding_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      taxonomy_topics: {
        Row: {
          id: string
          slug: string
          label: string
          parent_id: string | null
          source: string | null
          arxiv_category: string | null
          depth: number
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          slug: string
          label: string
          parent_id?: string | null
          source?: string | null
          arxiv_category?: string | null
          depth?: number
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          slug?: string
          label?: string
          parent_id?: string | null
          source?: string | null
          arxiv_category?: string | null
          depth?: number
          sort_order?: number
          created_at?: string
        }
        Relationships: []
      }
      topic_relations: {
        Row: {
          source_topic_id: string
          target_topic_id: string
          relation_type: string
          weight: number
          created_at: string
        }
        Insert: {
          source_topic_id: string
          target_topic_id: string
          relation_type: string
          weight?: number
          created_at?: string
        }
        Update: {
          source_topic_id?: string
          target_topic_id?: string
          relation_type?: string
          weight?: number
          created_at?: string
        }
        Relationships: []
      }
      papers: {
        Row: {
          id: string
          title: string
          abstract: string | null
          year: number | null
          published_at: string | null
          updated_at: string | null
          source: Database["public"]["Enums"]["paper_source"]
          doi: string | null
          arxiv_id: string | null
          semantic_scholar_id: string | null
          openalex_id: string | null
          url: string
          pdf_url: string | null
          venue: string | null
          citation_count: number | null
          is_open_access: boolean | null
          access: Database["public"]["Enums"]["paper_access"]
          is_classic: boolean
          embedding: string | number[] | null
          embedding_model: string | null
          embedding_dimension: number | null
          embedding_content_hash: string | null
          embedded_at: string | null
          triage_summary: Json | null
          triage_summary_model: string | null
          triage_summary_generated_at: string | null
          created_at: string
          ingested_at: string
        }
        Insert: {
          id?: string
          title: string
          abstract?: string | null
          year?: number | null
          published_at?: string | null
          updated_at?: string | null
          source: Database["public"]["Enums"]["paper_source"]
          doi?: string | null
          arxiv_id?: string | null
          semantic_scholar_id?: string | null
          openalex_id?: string | null
          url: string
          pdf_url?: string | null
          venue?: string | null
          citation_count?: number | null
          is_open_access?: boolean | null
          access?: Database["public"]["Enums"]["paper_access"]
          is_classic?: boolean
          embedding?: string | number[] | null
          embedding_model?: string | null
          embedding_dimension?: number | null
          embedding_content_hash?: string | null
          embedded_at?: string | null
          triage_summary?: Json | null
          triage_summary_model?: string | null
          triage_summary_generated_at?: string | null
          created_at?: string
          ingested_at?: string
        }
        Update: {
          id?: string
          title?: string
          abstract?: string | null
          year?: number | null
          published_at?: string | null
          updated_at?: string | null
          source?: Database["public"]["Enums"]["paper_source"]
          doi?: string | null
          arxiv_id?: string | null
          semantic_scholar_id?: string | null
          openalex_id?: string | null
          url?: string
          pdf_url?: string | null
          venue?: string | null
          citation_count?: number | null
          is_open_access?: boolean | null
          access?: Database["public"]["Enums"]["paper_access"]
          is_classic?: boolean
          embedding?: string | number[] | null
          embedding_model?: string | null
          embedding_dimension?: number | null
          embedding_content_hash?: string | null
          embedded_at?: string | null
          triage_summary?: Json | null
          triage_summary_model?: string | null
          triage_summary_generated_at?: string | null
          created_at?: string
          ingested_at?: string
        }
        Relationships: []
      }
      paper_authors: {
        Row: {
          id: string
          paper_id: string
          name: string
          position: number
          created_at: string
        }
        Insert: {
          id?: string
          paper_id: string
          name: string
          position?: number
          created_at?: string
        }
        Update: {
          id?: string
          paper_id?: string
          name?: string
          position?: number
          created_at?: string
        }
        Relationships: []
      }
      paper_topics: {
        Row: {
          paper_id: string
          topic_id: string
          confidence: number | null
          source: string | null
          created_at: string
        }
        Insert: {
          paper_id: string
          topic_id: string
          confidence?: number | null
          source?: string | null
          created_at?: string
        }
        Update: {
          paper_id?: string
          topic_id?: string
          confidence?: number | null
          source?: string | null
          created_at?: string
        }
        Relationships: []
      }
      paper_external_ids: {
        Row: {
          paper_id: string
          provider: string
          external_id: string
          url: string | null
          created_at: string
        }
        Insert: {
          paper_id: string
          provider: string
          external_id: string
          url?: string | null
          created_at?: string
        }
        Update: {
          paper_id?: string
          provider?: string
          external_id?: string
          url?: string | null
          created_at?: string
        }
        Relationships: []
      }
      topic_embeddings: {
        Row: {
          topic_id: string
          embedding: string | number[]
          embedding_model: string
          embedding_dimension: number
          embedding_content_hash: string
          embedded_at: string
        }
        Insert: {
          topic_id: string
          embedding: string | number[]
          embedding_model: string
          embedding_dimension: number
          embedding_content_hash: string
          embedded_at?: string
        }
        Update: {
          topic_id?: string
          embedding?: string | number[]
          embedding_model?: string
          embedding_dimension?: number
          embedding_content_hash?: string
          embedded_at?: string
        }
        Relationships: []
      }
      user_interests: {
        Row: {
          owner_id: string
          topic_id: string
          weight: number
          selected_at: string
        }
        Insert: {
          owner_id: string
          topic_id: string
          weight?: number
          selected_at?: string
        }
        Update: {
          owner_id?: string
          topic_id?: string
          weight?: number
          selected_at?: string
        }
        Relationships: []
      }
      user_profile_embeddings: {
        Row: {
          owner_id: string
          embedding: string | number[]
          embedding_model: string
          embedding_dimension: number
          input_signature: string
          generated_at: string
        }
        Insert: {
          owner_id: string
          embedding: string | number[]
          embedding_model: string
          embedding_dimension: number
          input_signature: string
          generated_at?: string
        }
        Update: {
          owner_id?: string
          embedding?: string | number[]
          embedding_model?: string
          embedding_dimension?: number
          input_signature?: string
          generated_at?: string
        }
        Relationships: []
      }
      playlists: {
        Row: {
          id: string
          owner_id: string
          name: string
          description: string | null
          is_default: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          description?: string | null
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          description?: string | null
          is_default?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      playlist_items: {
        Row: {
          playlist_id: string
          paper_id: string
          position: number
          added_at: string
        }
        Insert: {
          playlist_id: string
          paper_id: string
          position?: number
          added_at?: string
        }
        Update: {
          playlist_id?: string
          paper_id?: string
          position?: number
          added_at?: string
        }
        Relationships: []
      }
      favorites: {
        Row: {
          owner_id: string
          paper_id: string
          created_at: string
        }
        Insert: {
          owner_id: string
          paper_id: string
          created_at?: string
        }
        Update: {
          owner_id?: string
          paper_id?: string
          created_at?: string
        }
        Relationships: []
      }
      user_paper_interactions: {
        Row: {
          id: string
          owner_id: string
          paper_id: string
          action: Database["public"]["Enums"]["interaction_type"]
          context: string
          created_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          paper_id: string
          action: Database["public"]["Enums"]["interaction_type"]
          context?: string
          created_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          paper_id?: string
          action?: Database["public"]["Enums"]["interaction_type"]
          context?: string
          created_at?: string
        }
        Relationships: []
      }
      recommendations: {
        Row: {
          id: string
          owner_id: string
          paper_id: string
          score: number
          reason: string | null
          model_version: string | null
          generated_at: string
          seen_at: string | null
        }
        Insert: {
          id?: string
          owner_id: string
          paper_id: string
          score: number
          reason?: string | null
          model_version?: string | null
          generated_at?: string
          seen_at?: string | null
        }
        Update: {
          id?: string
          owner_id?: string
          paper_id?: string
          score?: number
          reason?: string | null
          model_version?: string | null
          generated_at?: string
          seen_at?: string | null
        }
        Relationships: []
      }
      digests: {
        Row: {
          id: string
          owner_id: string
          title: string
          generated_at: string
          viewed_at: string | null
        }
        Insert: {
          id?: string
          owner_id: string
          title: string
          generated_at?: string
          viewed_at?: string | null
        }
        Update: {
          id?: string
          owner_id?: string
          title?: string
          generated_at?: string
          viewed_at?: string | null
        }
        Relationships: []
      }
      digest_items: {
        Row: {
          digest_id: string
          paper_id: string
          position: number
          reason: string | null
        }
        Insert: {
          digest_id: string
          paper_id: string
          position?: number
          reason?: string | null
        }
        Update: {
          digest_id?: string
          paper_id?: string
          position?: number
          reason?: string | null
        }
        Relationships: []
      }
      ingestion_runs: {
        Row: {
          id: string
          source: Database["public"]["Enums"]["paper_source"]
          status: string
          started_at: string
          finished_at: string | null
          cursor_value: string | null
          imported_count: number
          error_message: string | null
        }
        Insert: {
          id?: string
          source: Database["public"]["Enums"]["paper_source"]
          status: string
          started_at?: string
          finished_at?: string | null
          cursor_value?: string | null
          imported_count?: number
          error_message?: string | null
        }
        Update: {
          id?: string
          source?: Database["public"]["Enums"]["paper_source"]
          status?: string
          started_at?: string
          finished_at?: string | null
          cursor_value?: string | null
          imported_count?: number
          error_message?: string | null
        }
        Relationships: []
      }
      ingestion_cursors: {
        Row: {
          source: Database["public"]["Enums"]["paper_source"]
          cursor_key: string
          cursor_value: string | null
          last_seen_published_at: string | null
          last_seen_external_id: string | null
          last_successful_run_id: string | null
          imported_count: number
          updated_at: string
        }
        Insert: {
          source: Database["public"]["Enums"]["paper_source"]
          cursor_key: string
          cursor_value?: string | null
          last_seen_published_at?: string | null
          last_seen_external_id?: string | null
          last_successful_run_id?: string | null
          imported_count?: number
          updated_at?: string
        }
        Update: {
          source?: Database["public"]["Enums"]["paper_source"]
          cursor_key?: string
          cursor_value?: string | null
          last_seen_published_at?: string | null
          last_seen_external_id?: string | null
          last_successful_run_id?: string | null
          imported_count?: number
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      match_papers_by_embedding: {
        Args: {
          query_embedding: string | number[]
          match_count?: number
          embedding_model_filter?: string
        }
        Returns: Array<{
          paper_id: string
          semantic_score: number
        }>
      }
    }
    Enums: {
      paper_access: "open" | "publisher" | "unknown"
      paper_source: "arxiv" | "semantic_scholar" | "openalex" | "dblp" | "crossref" | "manual"
      interaction_type: "seen" | "open_detail" | "dismiss" | "favorite" | "save_to_playlist" | "read" | "not_interested" | "already_read"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
};

type PublicSchema = Database["public"];

export type Tables<TableName extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][TableName]["Row"];

export type TablesInsert<TableName extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][TableName]["Insert"];

export type TablesUpdate<TableName extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][TableName]["Update"];

export type Enums<EnumName extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][EnumName];
